/*
 * cert_store.c — TLS credential management (Phase 2)
 *
 * Two-step provisioning model
 * ────────────────────────────
 * Step 1 — conexio-stratus-provision (flash once per device):
 *   Runs AWS IoT Fleet Provisioning (CreateCertificateFromCsr + RegisterThing).
 *   Stores in modem NVM:
 *     Tag 100 — AWS Root CA            (CONFIG_CONEXIO_CLOUD_CA_TAG)
 *     Tag 101 — Device public cert     (CONFIG_CONEXIO_CLOUD_CERT_TAG)  ← AWS-issued
 *     Tag 102 — Device private key     (CONFIG_CONEXIO_CLOUD_KEY_TAG)   ← AT%KEYGEN (never leaves modem)
 *
 * Step 2 — samples/app (this application):
 *   Trusts that Step 1 has already been done.
 *   cert_store_provision_from_config() does two things:
 *     a) Writes the AWS Root CA to tag 100 if absent (embedded in firmware —
 *        the Root CA is public and static; safe to embed).
 *     b) Verifies that the device cert (tag 101) and private key (tag 102) are
 *        already present in the modem.  If either is missing the function
 *        returns -ENOENT with a clear error message — DO NOT attempt to write
 *        them here; re-flash conexio-stratus-provision instead.
 *
 * Why the Root CA is still embedded
 * ──────────────────────────────────
 * The device cert and key are unique per device and are provisioned dynamically
 * by the fleet provisioning flow.  The Root CA (AmazonRootCA1.pem) is the same
 * for every device and never changes — embedding it is safe and avoids an HTTPS
 * download on every fresh modem.
 *
 * write_if_absent() pattern
 * ─────────────────────────
 * Checks modem_key_mgmt_exists() before writing.  This protects modem NVM
 * write cycles (~10,000 per tag) and saves ~300 ms startup time on warm boots
 * where the cert is already present.
 */

#include <zephyr/kernel.h>
#include <modem/modem_key_mgmt.h>
#include <modem/lte_lc.h>
#include <zephyr/logging/log.h>
#include <string.h>
#include "cert_store.h"
#include "config_fetch.h"

LOG_MODULE_REGISTER(cert_store, LOG_LEVEL_INF);

/* ── Embedded AWS Root CA ────────────────────────────────────────────────────
 * Generated by CMake from samples/app/src/certs/AmazonRootCA1.pem at build time.
 * The Root CA is public, static, and identical for every device — safe to embed.
 * Device cert and key are NOT embedded here; they come from fleet provisioning.
 */
static const unsigned char aws_root_ca[] = {
#include "aws_root_ca.pem.inc"
};

/* ── write_if_absent ─────────────────────────────────────────────────────────
 * Write a credential only if the modem tag is currently empty.
 * modem_key_mgmt_write() requires the modem to be offline — this function
 * briefly takes it offline and returns it to normal mode.
 * On subsequent boots the credential is already present and the write is
 * skipped entirely (no offline transition, no NVM wear).
 */
static int write_if_absent(int tag, enum modem_key_mgmt_cred_type type,
                            const unsigned char *data, size_t len,
                            const char *label)
{
    bool exists = false;
    modem_key_mgmt_exists(tag, type, &exists);
    if (exists) {
        LOG_INF("%s already in modem (tag %d) — skipping", label, tag);
        return 0;
    }

    /* Need modem offline to write credentials */
    lte_lc_func_mode_set(LTE_LC_FUNC_MODE_OFFLINE);
    int ret = modem_key_mgmt_write(tag, type, data, len);
    lte_lc_func_mode_set(LTE_LC_FUNC_MODE_NORMAL);

    if (ret < 0) {
        LOG_ERR("Failed to write %s (tag %d): %d", label, tag, ret);
    } else {
        LOG_INF("%s written to modem (tag %d)", label, tag);
    }
    return ret;
}

/* ── cert_store_provision_from_config ────────────────────────────────────────
 * Called once by conexio_cloud_init() before LTE connects.
 *
 * 1. Ensures the AWS Root CA is in the modem (writes on first boot only).
 * 2. Verifies device cert + key were placed by conexio-stratus-provision.
 *    Returns -ENOENT if either is missing — the device must be re-provisioned.
 *
 * cfg is accepted for API compatibility but is unused — the Root CA is
 * embedded at compile time; dynamic download is not needed.
 */
int cert_store_provision_from_config(const struct conexio_cloud_config_t *cfg)
{
    ARG_UNUSED(cfg);
    int ret;

    /* ── 1. AWS Root CA (tag 100) — write-once from embedded firmware ── */
    ret = write_if_absent(CONFIG_CONEXIO_CLOUD_CA_TAG,
                          MODEM_KEY_MGMT_CRED_TYPE_CA_CHAIN,
                          aws_root_ca, sizeof(aws_root_ca) - 1,
                          "AWS Root CA");
    if (ret < 0) {
        return ret;
    }

    /* ── 2. Device cert (tag 101) — must exist from fleet provisioning ── */
    bool cert_exists = false;
    ret = modem_key_mgmt_exists(CONFIG_CONEXIO_CLOUD_CERT_TAG,
                                MODEM_KEY_MGMT_CRED_TYPE_PUBLIC_CERT,
                                &cert_exists);
    if (ret < 0) {
        LOG_ERR("modem_key_mgmt_exists failed for device cert (tag %d): %d",
                CONFIG_CONEXIO_CLOUD_CERT_TAG, ret);
        return ret;
    }
    if (!cert_exists) {
        LOG_ERR("Device certificate not found in modem (tag %d).",
                CONFIG_CONEXIO_CLOUD_CERT_TAG);
        LOG_ERR("Flash and run conexio-stratus-provision first to provision "
                "this device, then re-flash this application.");
        return -ENOENT;
    }
    LOG_INF("Device cert present in modem (tag %d)", CONFIG_CONEXIO_CLOUD_CERT_TAG);

    /* ── 3. Device private key (tag 102) — must exist from AT%%KEYGEN ── */
    bool key_exists = false;
    ret = modem_key_mgmt_exists(CONFIG_CONEXIO_CLOUD_KEY_TAG,
                                MODEM_KEY_MGMT_CRED_TYPE_PRIVATE_CERT,
                                &key_exists);
    if (ret < 0) {
        LOG_ERR("modem_key_mgmt_exists failed for device key (tag %d): %d",
                CONFIG_CONEXIO_CLOUD_KEY_TAG, ret);
        return ret;
    }
    if (!key_exists) {
        LOG_ERR("Device private key not found in modem (tag %d).",
                CONFIG_CONEXIO_CLOUD_KEY_TAG);
        LOG_ERR("Flash and run conexio-stratus-provision first to provision "
                "this device, then re-flash this application.");
        return -ENOENT;
    }
    LOG_INF("Device private key present in modem (tag %d)", CONFIG_CONEXIO_CLOUD_KEY_TAG);

    LOG_INF("All TLS credentials verified — Root CA (tag %d), "
            "cert (tag %d), key (tag %d)",
            CONFIG_CONEXIO_CLOUD_CA_TAG,
            CONFIG_CONEXIO_CLOUD_CERT_TAG,
            CONFIG_CONEXIO_CLOUD_KEY_TAG);
    return 0;
}
