/*
 * cert_store.c — TLS credential management (Phase 2)
 *
 * Uses write_if_absent() — certificates are embedded at build time and written
 * to the modem only on the first boot. Subsequent boots skip the write entirely
 * so the modem never needs to be taken offline after the initial provisioning.
 *
 * Certificate layout in modem NVM (security tag numbers):
 *   Tag 100 — AWS Root CA            (CONFIG_CONEXIO_CLOUD_CA_TAG)
 *   Tag 101 — Device public cert     (CONFIG_CONEXIO_CLOUD_CERT_TAG)
 *   Tag 102 — Device private key     (CONFIG_CONEXIO_CLOUD_KEY_TAG)
 *
 * Certs are embedded via generate_inc_file_for_target() in the app
 * CMakeLists.txt, the same pattern as the mqtt sample.
 */

#include <zephyr/kernel.h>
#include <modem/modem_key_mgmt.h>
#include <modem/lte_lc.h>
#include <zephyr/logging/log.h>
#include <string.h>
#include "cert_store.h"
#include "config_fetch.h"

LOG_MODULE_REGISTER(cert_store, LOG_LEVEL_INF);

/* ── Embedded certificates ───────────────────────────────────────────────────
 * Generated by CMake from samples/app/src/certs/*.pem at build time.
 * Place AmazonRootCA1.pem, device.crt, and device.key in src/certs/
 * before building.
 */
static const unsigned char aws_root_ca[] = {
#include "aws_root_ca.pem.inc"
};

static const unsigned char aws_device_cert[] = {
#include "aws_device_cert.pem.inc"
};

static const unsigned char aws_device_key[] = {
#include "aws_device_key.pem.inc"
};

/* ── write_if_absent ─────────────────────────────────────────────────────────
 * Write a credential only if the tag is empty.
 * modem_key_mgmt_write requires offline mode — only called when the credential
 * is genuinely absent (first boot or after factory reset).
 */
static int write_if_absent(int tag, enum modem_key_mgmt_cred_type type,
                            const unsigned char *data, size_t len,
                            const char *label)
{
    bool exists = false;
    modem_key_mgmt_exists(tag, type, &exists);
    if (exists) {
        LOG_INF("%s already in modem (tag %d) — skipping", label, tag);
        return 0;
    }

    /* Need modem offline to write credentials */
    lte_lc_func_mode_set(LTE_LC_FUNC_MODE_OFFLINE);
    int ret = modem_key_mgmt_write(tag, type, data, len);
    lte_lc_func_mode_set(LTE_LC_FUNC_MODE_NORMAL);

    if (ret < 0) {
        LOG_ERR("Failed to write %s (tag %d): %d", label, tag, ret);
    } else {
        LOG_INF("%s written to modem (tag %d)", label, tag);
    }
    return ret;
}

/* ── cert_store_provision_from_config ────────────────────────────────────────
 * Called once by conexio_cloud_init() after config_fetch() succeeds.
 * cfg is provided for API compatibility but the certs are embedded — the
 * root_ca_url in cfg is not used here.
 */
int cert_store_provision_from_config(const struct conexio_cloud_config_t *cfg)
{
    ARG_UNUSED(cfg);
    int ret;

    LOG_INF("Provisioning TLS credentials...");

    ret = write_if_absent(CONFIG_CONEXIO_CLOUD_CA_TAG,
                          MODEM_KEY_MGMT_CRED_TYPE_CA_CHAIN,
                          aws_root_ca, sizeof(aws_root_ca) - 1,
                          "Root CA");
    if (ret < 0) return ret;

    ret = write_if_absent(CONFIG_CONEXIO_CLOUD_CERT_TAG,
                          MODEM_KEY_MGMT_CRED_TYPE_PUBLIC_CERT,
                          aws_device_cert, sizeof(aws_device_cert) - 1,
                          "Device cert");
    if (ret < 0) return ret;

    ret = write_if_absent(CONFIG_CONEXIO_CLOUD_KEY_TAG,
                          MODEM_KEY_MGMT_CRED_TYPE_PRIVATE_CERT,
                          aws_device_key, sizeof(aws_device_key) - 1,
                          "Device key");
    if (ret < 0) return ret;

    LOG_INF("All TLS credentials ready");
    return 0;
}
