/*
 * aws_certs.c — Provisions TLS credentials into the nRF91xx modem.
 *
 * Uses write_if_absent() so credentials are only written on the very first
 * boot (or after a factory reset). Subsequent boots skip the write, which
 * means the modem does NOT need to be taken offline on every boot.
 */

#include <zephyr/kernel.h>
#include <modem/modem_key_mgmt.h>
#include <zephyr/logging/log.h>
#include "aws_certs.h"

LOG_MODULE_REGISTER(aws_certs, LOG_LEVEL_INF);

/* Embedded certificate content — generated by CMake from src/certs/*.pem */
static const unsigned char aws_root_ca[] = {
#include "aws_root_ca.pem.inc"
};

static const unsigned char aws_device_cert[] = {
#include "aws_device_cert.pem.inc"
};

static const unsigned char aws_device_key[] = {
#include "aws_device_key.pem.inc"
};

/* Write a credential only if the slot is empty — avoids unnecessary
 * modem offline/online cycles on every boot. */
static int write_if_absent(int tag, enum modem_key_mgmt_cred_type type,
                            const unsigned char *data, size_t len,
                            const char *label)
{
    bool exists = false;
    modem_key_mgmt_exists(tag, type, &exists);
    if (exists) {
        LOG_INF("%s already in modem (tag %d) — skipping", label, tag);
        return 0;
    }
    int ret = modem_key_mgmt_write(tag, type, data, len);
    if (ret < 0) {
        LOG_ERR("Failed to write %s (tag %d): %d", label, tag, ret);
    } else {
        LOG_INF("%s written (tag %d)", label, tag);
    }
    return ret;
}

int aws_certs_provision(void)
{
    int ret;

    LOG_INF("Provisioning TLS credentials...");

    ret = write_if_absent(AWS_CA_TAG,
                          MODEM_KEY_MGMT_CRED_TYPE_CA_CHAIN,
                          aws_root_ca, sizeof(aws_root_ca) - 1,
                          "Root CA");
    if (ret < 0) return ret;

    ret = write_if_absent(AWS_CERT_TAG,
                          MODEM_KEY_MGMT_CRED_TYPE_PUBLIC_CERT,
                          aws_device_cert, sizeof(aws_device_cert) - 1,
                          "Device cert");
    if (ret < 0) return ret;

    ret = write_if_absent(AWS_KEY_TAG,
                          MODEM_KEY_MGMT_CRED_TYPE_PRIVATE_CERT,
                          aws_device_key, sizeof(aws_device_key) - 1,
                          "Device key");
    if (ret < 0) return ret;

    LOG_INF("TLS credentials ready");
    return 0;
}
