/*
 * aws_certs.c — Provisions TLS credentials into the nRF91xx modem.
 *
 * The three PEM files in src/certs/ are embedded as binary arrays at build
 * time by CMakeLists.txt using generate_inc_file_for_target().
 *
 * Call aws_certs_provision() once at startup before connecting to AWS.
 */

#include <zephyr/kernel.h>
#include <modem/modem_key_mgmt.h>
#include <zephyr/logging/log.h>
#include "aws_certs.h"

LOG_MODULE_REGISTER(aws_certs, LOG_LEVEL_INF);

/* Embedded certificate content — generated by CMake from src/certs/*.pem */
static const unsigned char aws_root_ca[] = {
#include "aws_root_ca.pem.inc"
};

static const unsigned char aws_device_cert[] = {
#include "aws_device_cert.pem.inc"
};

static const unsigned char aws_device_key[] = {
#include "aws_device_key.pem.inc"
};

int aws_certs_provision(void)
{
    int ret;

    LOG_INF("Provisioning TLS credentials into modem...");

    /* Overwrite any existing credentials with the same tags */
    ret = modem_key_mgmt_write(AWS_CA_TAG,
                               MODEM_KEY_MGMT_CRED_TYPE_CA_CHAIN,
                               aws_root_ca,
                               sizeof(aws_root_ca) - 1); /* -1: exclude null terminator */
    if (ret < 0) {
        LOG_ERR("Failed to provision Root CA (err %d)", ret);
        return ret;
    }
    LOG_INF("Root CA provisioned (tag %d)", AWS_CA_TAG);

    ret = modem_key_mgmt_write(AWS_CERT_TAG,
                               MODEM_KEY_MGMT_CRED_TYPE_PUBLIC_CERT,
                               aws_device_cert,
                               sizeof(aws_device_cert) - 1);
    if (ret < 0) {
        LOG_ERR("Failed to provision device certificate (err %d)", ret);
        return ret;
    }
    LOG_INF("Device certificate provisioned (tag %d)", AWS_CERT_TAG);

    ret = modem_key_mgmt_write(AWS_KEY_TAG,
                               MODEM_KEY_MGMT_CRED_TYPE_PRIVATE_CERT,
                               aws_device_key,
                               sizeof(aws_device_key) - 1);
    if (ret < 0) {
        LOG_ERR("Failed to provision private key (err %d)", ret);
        return ret;
    }
    LOG_INF("Private key provisioned (tag %d)", AWS_KEY_TAG);

    LOG_INF("TLS credentials provisioned successfully");
    return 0;
}
